apiVersion: v1
kind: Service
metadata:
  name: web-api-service
  namespace: test-development
spec:
  selector:
    app: web-api
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 8000