apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: web-api-app-cert
  namespace: test-development
spec:
  dnsNames:
    - webapi.sakaryaprojwebapi.xyz
  secretName: web-api-app-tls
  issuerRef:
    name: letsencrypt-cluster-issuer
    kind: ClusterIssuer