apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: test-development
type: Opaque
data:
  CONSUMER_KEY: test
  CONSUMER_SECRET: test
  ACCESS_TOKEN_KEY: test
  ACCESS_TOKEN_KEY_SECRET: test
