apiVersion: v1
kind: ConfigMap
metadata:
  name: app-conn
  namespace: test-development
data:
  LOGSTASH_HOST: "logstash.default.svc.cluster.local"
  CONSUMER_KEY: test
  CONSUMER_SECRET: test
  ACCESS_TOKEN_KEY: test
  ACCESS_TOKEN_KEY_SECRET: test
  KAFKA_HOST: localhost